global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.gmail.com:587' # Endereço e porta do servidor SMTP do Google
  smtp_from: $SOURCE_EMAIL      # Endereço de e-mail do remetente (deve ser uma conta do Gmail)
  smtp_auth_username: $GOOGLE_ACCOUNT  # Seu e-mail do Gmail
  smtp_auth_password: $GOOGLE_AUTH
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: $TARGET_EMAIL
        send_resolved: true
        html: |
          <html>
          <body>
            <h1>Alertmanager Alert</h1>
            <p><b>Alert:</b> {{ .CommonAnnotations.summary }}</p>
            <p><b>Description:</b> {{ .CommonAnnotations.description }}</p>
            <p><b>Alert Details:</b></p>
            <ul>
              {{ range .Alerts }}
                <li><b>Alert:</b> {{ .Annotations.summary }} - <i>{{ .Annotations.description }}</i></li>
              {{ end }}
            </ul>
          </body>
          </html>